volumes:
  db_data:

services:

  app:
    build:
        context: .
        dockerfile: .docker/service/Dockerfile
    ports:
      - 8081:80
      - 2222:22
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1  # Print logs in real-time

  db:
    image: ankane/pgvector:v0.5.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data
      - .docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d vectordb" ]
      interval: 10s
      timeout: 5s
      retries: 5