services:
  service:
    build:
        context: .
        dockerfile: .docker/service/Dockerfile
    ports:
      - 8081:80
      - 2222:22
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1  # Print logs in real-time
